### ISSUE TITLE
pyGard Not working in python 3.5

### ISSUE THREAD

**Issue by prelard812** [crafti5/pyGARD#1]
Just install pyGard and got problem in python 3.5.   
I found that as we are playing with text file: the open file function must be used in text format. So I change 
the line #80 from : **return open(path, 'rb').read()**  to **return open(path, 'r').read()**
the line #86 from : **with open(self.output_name, 'wb') as file:**   to  **with open(self.output_name, 'w') as file:**

and boom it is now working

**Comment by StephanKa** [comment]
Thanks for your hint and excuse my late response ;)

Fixed: 4a086f96d20631fce0b8a56b668e53db3f739736
